prometheus:
  prometheusSpec:
    retention: 15d
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

alertmanager:
  alertmanagerSpec:
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 100Mi

grafana:
  adminPassword: "admin"
  resources:
    limits:
      cpu: 200m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 200Mi
  ingress:
    enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
